[project]
name = "mhc-rankings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brakedust", email = "brakedust7@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "markdown-it-py>=4.2.0",
    "matplotlib>=3.10.9",
    "mdit-py-plugins>=0.6.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "plotly>=6.7.0",
]

[project.scripts]
mhc-rankings = "mhc_rankings:main"
mkdoc = "mhc_rankings.mkdoc:main"

[build-system]
requires = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.0",
]
